"""
PDF / Text-based Threat Intelligence Report Generator.
Fixed: 'Not enough horizontal space' caused by cell()+multi_cell(0) pattern.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, Any

from config.settings import REPORTS_DIR

try:
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


def _hex_to_rgb(hex_color: str):
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def _safe(text: str) -> str:
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2019": "'", "\u2018": "'",
        "\u201c": '"', "\u201d": '"', "\u2022": "*", "\u2588": "#",
        "\u2500": "-", "\u00a0": " ",
    }
    for char, rep in replacements.items():
        text = text.replace(char, rep)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class ThreatReportPDF(FPDF if FPDF_AVAILABLE else object):
    def header(self):
        self.set_fill_color(13, 71, 161)
        self.rect(0, 0, 210, 16, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 12)
        self.set_xy(10, 3)
        self.cell(0, 10, "CyberGuard AI - Threat Intelligence Report",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 6,
                  f"CONFIDENTIAL - Page {self.page_no()} | Generated by CyberGuard AI",
                  align="C")


def generate_pdf_report(report: Dict[str, Any]) -> str:
    if not FPDF_AVAILABLE:
        return generate_text_report(report)

    pdf = ThreatReportPDF()
    pdf.set_margins(20, 28, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    W = pdf.w - pdf.l_margin - pdf.r_margin  # usable width ~170mm

    threat     = _safe(str(report.get("threat", "Unknown")))
    severity   = _safe(str(report.get("severity_level", "Unknown")))
    confidence = report.get("confidence", 0)
    risk_score = report.get("risk_score", 0)
    ts         = _safe(str(report.get("timestamp", datetime.now().isoformat())))
    model_src  = _safe(str(report.get("model_source", "N/A")).upper())
    sev_rgb    = _hex_to_rgb(report.get("severity_color", "#00C853"))

    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*sev_rgb)
    pdf.cell(W, 10, f"Threat Classification: {threat}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(W, 6, f"Timestamp: {ts}  |  Model: {model_src}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    def section_header(title: str):
        pdf.set_fill_color(21, 101, 192)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(W, 7, f"  {_safe(title)}", fill=True,
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

    def kv_row(key: str, value: str, alt: bool = False):
        key_w = 52
        val_w = W - key_w
        pdf.set_fill_color(*(240, 245, 255) if alt else (255, 255, 255))
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(key_w, 7, f"  {_safe(key)}", fill=True)
        pdf.set_font("Helvetica", "", 9)
        # KEY FIX: explicit val_w, never 0 after a cell()
        pdf.multi_cell(val_w, 7, _safe(str(value)), fill=True)

    def numbered_multi(index: int, text: str):
        # KEY FIX: combine number+text into ONE multi_cell with full W
        # Old broken: cell(8)+multi_cell(0) -> 0 = tiny remaining width = crash
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(W, 6, _safe(f"{index}. {text}"))

    section_header("Executive Summary")
    kv_row("Threat Type",      threat,               alt=True)
    kv_row("Severity Level",   severity)
    kv_row("Confidence Score", f"{confidence:.1f}%", alt=True)
    kv_row("Risk Score",       f"{risk_score}/100")
    pdf.ln(4)

    section_header("Classification Probabilities")
    probs = report.get("probabilities", {})
    alt = True
    for cls, prob in sorted(probs.items(), key=lambda x: -x[1]):
        kv_row(cls, f"{prob:.2f}%  {'#' * int(prob / 5)}", alt=alt)
        alt = not alt
    pdf.ln(4)

    section_header("Extracted Entities (NER)")
    entities = report.get("entities", {})
    entity_labels = {"urls": "URLs", "ips": "IP Addresses",
                     "emails": "Emails", "cves": "CVEs", "hashes": "File Hashes"}
    alt = True
    for k, label in entity_labels.items():
        items = entities.get(k, [])
        kv_row(label, ", ".join(items) if items else "None detected", alt=alt)
        alt = not alt
    pdf.ln(4)

    section_header("Cyber Threat Keywords Detected")
    top_kws = report.get("top_keywords", [])
    pdf.set_font("Helvetica", "" if top_kws else "I", 9)
    if top_kws:
        pdf.multi_cell(W, 6, _safe(" | ".join([f"{kw} [{cat}]" for kw, cat in top_kws])))
    else:
        pdf.cell(W, 7, "  No threat-specific keywords detected.",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    section_header("Explainable AI Reasoning")
    for i, reason in enumerate(report.get("reasoning", []), 1):
        numbered_multi(i, reason)
    pdf.ln(4)

    section_header("Recommended Actions")
    for i, rec in enumerate(report.get("recommendations", []), 1):
        numbered_multi(i, rec)
    pdf.ln(4)

    section_header("Analyzed Text (excerpt)")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_fill_color(245, 245, 245)
    pdf.multi_cell(W, 5, _safe(str(report.get("raw_text", ""))[:600]), fill=True)

    fname = f"threat_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    out_path = REPORTS_DIR / fname
    pdf.output(str(out_path))
    return str(out_path)


def generate_text_report(report: Dict[str, Any]) -> str:
    sep = "=" * 70
    lines = [sep, "  CYBERGUARD AI - CYBER THREAT INTELLIGENCE REPORT", sep,
             f"Timestamp   : {report.get('timestamp')}",
             f"Threat Type : {report.get('threat')}",
             f"Severity    : {report.get('severity_level')}",
             f"Confidence  : {report.get('confidence')}%",
             f"Risk Score  : {report.get('risk_score')}/100", "", "--- PROBABILITIES ---"]
    for cls, prob in sorted(report.get("probabilities", {}).items(), key=lambda x: -x[1]):
        lines.append(f"  {cls:<20}: {prob:.2f}%")
    lines += ["", "--- ENTITIES ---"]
    for k, v in report.get("entities", {}).items():
        lines.append(f"  {k.upper():<12}: {', '.join(v) if v else 'None'}")
    lines += ["", "--- REASONING ---"]
    for i, r in enumerate(report.get("reasoning", []), 1):
        lines.append(f"  {i}. {r}")
    lines += ["", "--- RECOMMENDATIONS ---"]
    for i, r in enumerate(report.get("recommendations", []), 1):
        lines.append(f"  {i}. {r}")
    lines += ["", sep]
    fname = f"threat_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    out_path = REPORTS_DIR / fname
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return str(out_path)
